<?php
/**
 * GENERATED by bin/generate-edition.php from every
 * inc/extensions/src/controls/<dir>/attributes.json - DO NOT EDIT. Regenerate
 * after any sidecar change; bin/wiring-check.php fails Quality CI and the dist
 * build when this file is stale.
 *
 * Every extension's block attributes — names, types, defaults — keyed by the
 * unit that owns the extension, registered on the core blocks by
 * inc/extensions/loader/attribute-schema.php in BOTH editions, so a page saved
 * in either edition writes back every attribute it was opened with (#858).
 * Each attribute is written in the compact form the registrar expands
 * (blocklane_pro_ext_attribute_definition()): 'name' => 'type' when it has
 * only a type, 'name' => array( 'type', default ) when it also has a default,
 * and the sidecar's full map for anything else.
 * IDENTICAL BYTES in both editions: this is data preservation, never a
 * capability, and it declares no control, no save filter, no render and no
 * stylesheet.
 *
 * DATA ONLY. No functional code may appear here.
 *
 * @package blocklane_pro
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'extension:advanced-grid' => array(
		array(
			'blocks' => array(
				'core/group',
				'core/post-template',
				'core/term-template',
			),
			'attributes' => array(
				'gridBreakpoints' => array(
					'array',
					array(),
				),
				'gridBreakpointSettings' => array(
					'object',
					array(),
				),
			),
		),
	),
	'extension:advanced-group' => array(
		array(
			'blocks' => array(
				'core/group',
				'core/column',
				'core/cover',
			),
			'attributes' => array(
				'href' => 'string',
				'linkDestination' => 'string',
				'linkTarget' => 'string',
			),
		),
		array(
			'blocks' => array(
				'core/group',
			),
			'attributes' => array(
				'stickyScrollOffset' => array(
					'string',
					'0px',
				),
				'stickyZIndex' => array(
					'number',
					NULL,
				),
				'stickyOnScrollUp' => array(
					'boolean',
					false,
				),
				'unstickOnMobile' => array(
					'boolean',
					false,
				),
				'blocklaneProMaxWidth' => 'string',
				'blocklaneProMaxWidthCenter' => array(
					'boolean',
					false,
				),
			),
		),
	),
	'extension:advanced-tabs' => array(
		array(
			'blocks' => array(
				'core/tab-panel',
			),
			'attributes' => array(
				'blocklaneProTabDescription' => array(
					'string',
					'',
				),
			),
		),
		array(
			'blocks' => array(
				'core/tab-list',
			),
			'attributes' => array(
				'blocklaneProTabDescriptionFontSize' => array(
					'string',
					'',
				),
			),
		),
		array(
			'blocks' => array(
				'core/tabs',
			),
			'attributes' => array(
				'blocklaneProTabListPosition' => array(
					'string',
					'',
				),
				'blocklaneProTabListVerticalAlignment' => array(
					'string',
					'',
				),
				'blocklaneProTabListWidth' => array(
					'number',
					0,
				),
				'blocklaneProTabDescriptionsAlwaysVisible' => array(
					'boolean',
					false,
				),
			),
		),
	),
	'extension:animation-designer' => array(
		array(
			'blocks' => array(
				'core/group',
				'core/heading',
				'core/paragraph',
				'core/column',
				'core/columns',
				'core/image',
				'core/buttons',
				'core/cover',
				'core/post-template',
			),
			'attributes' => array(
				'animationType' => array(
					'string',
					'',
				),
				'animationDuration' => array(
					'number',
					1,
				),
				'animationDelay' => array(
					'number',
					0,
				),
				'animationDistance' => array(
					'number',
					30,
				),
				'animationScale' => array(
					'number',
					1.05,
				),
				'animateOnScroll' => array(
					'boolean',
					false,
				),
				'animateOnce' => array(
					'boolean',
					true,
				),
				'scrollOffset' => array(
					'number',
					-50,
				),
				'animationPresetId' => array(
					'string',
					'',
				),
				'animateSequentially' => array(
					'boolean',
					false,
				),
				'sequentialDelay' => array(
					'number',
					0.2,
				),
				'wordDelay' => array(
					'number',
					0.2,
				),
			),
		),
	),
	'extension:button-icons' => array(
		array(
			'blocks' => array(
				'core/button',
			),
			'attributes' => array(
				'icon' => 'string',
				'iconPositionLeft' => array(
					'boolean',
					false,
				),
				'iconWeight' => array(
					'string',
					'regular',
				),
				'iconColor' => 'string',
				'customIconColor' => 'string',
				'iconSize' => 'string',
				'iconSpacing' => 'string',
				'customIconSvg' => array(
					'string',
					'',
				),
			),
		),
	),
	'extension:class-manager' => array(
		array(
			'blocks' => '*',
			'attributes' => array(
				'blocklaneProCustomClasses' => array(
					'array',
					array(),
				),
			),
		),
	),
	'extension:hover-colors' => array(
		array(
			'blocks' => array(
				'support' => 'color.text',
			),
			'attributes' => array(
				'hoverTextColor' => 'string',
				'customHoverTextColor' => 'string',
				'hoverBackgroundColor' => 'string',
				'customHoverBackgroundColor' => 'string',
				'hoverBorderColor' => 'string',
				'customHoverBorderColor' => 'string',
				'hoverTransitionDuration' => array(
					'number',
					200,
				),
				'hoverTransitionTiming' => array(
					'string',
					'ease',
				),
			),
		),
	),
	'extension:paragraph-hover-decoration' => array(
		array(
			'blocks' => array(
				'core/paragraph',
				'core/heading',
				'core/button',
			),
			'attributes' => array(
				'textDecorationHover' => array(
					'string',
					'',
				),
			),
		),
	),
	'extension:popup-binding' => array(
		array(
			'blocks' => array(
				'core/image',
				'core/cover',
			),
			'attributes' => array(
				'blocklaneProPopupId' => array(
					'number',
					0,
				),
			),
		),
		array(
			'blocks' => array(
				'core/button',
			),
			'attributes' => array(
				'blocklaneProPopupClose' => array(
					'boolean',
					false,
				),
			),
		),
	),
	'extension:responsive-controls' => array(
		array(
			'blocks' => array(
				'core/paragraph',
				'core/heading',
				'core/list',
				'core/quote',
				'core/button',
				'core/site-title',
				'core/group',
				'core/columns',
				'core/column',
				'core/cover',
				'core/buttons',
				'core/post-content',
				'core/site-logo',
				'core/navigation',
				'core/image',
				'core/social-links',
				'core/search',
				'core/separator',
				'core/spacer',
			),
			'attributes' => array(
				'blocklaneProResponsive' => array(
					'object',
					array(),
				),
			),
		),
	),
	'extension:smart-sync' => array(
		array(
			'blocks' => array(
				'core/columns',
				'core/group',
			),
			'attributes' => array(
				'smartSync' => array(
					'boolean',
					false,
				),
			),
		),
	),
	'extension:text-wrap' => array(
		array(
			'blocks' => array(
				'core/paragraph',
				'core/heading',
				'core/list',
				'core/post-title',
				'core/post-excerpt',
			),
			'attributes' => array(
				'textWrap' => array(
					'string',
					'',
				),
			),
		),
	),
	'extension:transparent-header' => array(
		array(
			'blocks' => array(
				'core/group',
			),
			'attributes' => array(
				'blocklaneProTransparentHeader' => array(
					'boolean',
					false,
				),
				'blocklaneProThBackground' => array(
					'string',
					'',
				),
				'blocklaneProTransparentSolidOnScroll' => array(
					'boolean',
					true,
				),
				'blocklaneProTransparentTopOffset' => 'string',
				'blocklaneProTransparentZIndex' => 'number',
				'blocklaneProTransparentBackground' => 'string',
				'blocklaneProTransparentTextColor' => 'string',
				'blocklaneProTransparentLogo' => 'string',
			),
		),
		array(
			'blocks' => array(
				'core/group',
			),
			'attributes' => array(
				'blocklaneProThSolidBackground' => 'string',
			),
		),
		array(
			'blocks' => array(
				'core/navigation',
			),
			'attributes' => array(
				'blocklaneProTransparentTextColor' => 'string',
				'blocklaneProTransparentHoverColor' => 'string',
				'blocklaneProTransparentCurrentColor' => 'string',
			),
		),
		array(
			'blocks' => array(
				'core/site-title',
				'core/site-tagline',
				'core/search',
				'core/loginout',
			),
			'attributes' => array(
				'blocklaneProTransparentTextColor' => 'string',
			),
		),
		array(
			'blocks' => array(
				'core/button',
			),
			'attributes' => array(
				'blocklaneProTransparentTextColor' => 'string',
				'blocklaneProTransparentBackground' => 'string',
			),
		),
		array(
			'blocks' => array(
				'core/social-links',
			),
			'attributes' => array(
				'blocklaneProTransparentIconColor' => 'string',
				'blocklaneProTransparentIconBackground' => 'string',
			),
		),
		array(
			'blocks' => array(
				'core/site-logo',
			),
			'attributes' => array(
				'blocklaneProTransparentLogo' => 'string',
				'blocklaneProTransparentLogoId' => 'number',
			),
		),
	),
	'extension:video-modal' => array(
		array(
			'blocks' => array(
				'core/cover',
				'core/button',
				'core/image',
			),
			'attributes' => array(
				'blocklaneProVideoModal' => array(
					'boolean',
					false,
				),
				'blocklaneProVideoSource' => array(
					'string',
					'youtube',
				),
				'blocklaneProVideoUrl' => array(
					'string',
					'',
				),
				'blocklaneProVideoId' => array(
					'number',
					0,
				),
				'blocklaneProVideoAutoplay' => array(
					'boolean',
					true,
				),
				'blocklaneProVideoStartTime' => array(
					'number',
					0,
				),
				'blocklaneProPlayIcon' => array(
					'string',
					'always',
				),
			),
		),
	),
);
