<?php
/**
 * GENERATED by bin/generate-edition.php from every
 * inc/extensions/src/controls/<dir>/attributes.json - DO NOT EDIT. Regenerate
 * after any sidecar change; bin/wiring-check.php fails Quality CI and the dist
 * build when this file is stale.
 *
 * Every extension's block attributes — names, types, defaults — keyed by the
 * unit that owns the extension, registered on the core blocks by
 * inc/extensions/loader/attribute-schema.php in BOTH editions, so a page saved
 * in either edition writes back every attribute it was opened with (#858).
 * IDENTICAL BYTES in both editions: this is data preservation, never a
 * capability, and it declares no control, no save filter, no render and no
 * stylesheet.
 *
 * DATA ONLY. No functional code may appear here.
 *
 * @package blocklane_pro
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'extension:advanced-grid' => array(
		array(
			'blocks' => array(
				'core/group',
				'core/post-template',
				'core/term-template',
			),
			'attributes' => array(
				'gridBreakpoints' => array(
					'type' => 'array',
					'default' => array(),
				),
				'gridBreakpointSettings' => array(
					'type' => 'object',
					'default' => array(),
				),
			),
		),
	),
	'extension:advanced-group' => array(
		array(
			'blocks' => array(
				'core/group',
				'core/column',
				'core/cover',
			),
			'attributes' => array(
				'href' => array(
					'type' => 'string',
				),
				'linkDestination' => array(
					'type' => 'string',
				),
				'linkTarget' => array(
					'type' => 'string',
				),
			),
		),
		array(
			'blocks' => array(
				'core/group',
			),
			'attributes' => array(
				'stickyScrollOffset' => array(
					'type' => 'string',
					'default' => '0px',
				),
				'stickyZIndex' => array(
					'type' => 'number',
					'default' => NULL,
				),
				'stickyOnScrollUp' => array(
					'type' => 'boolean',
					'default' => false,
				),
				'unstickOnMobile' => array(
					'type' => 'boolean',
					'default' => false,
				),
				'blocklaneProMaxWidth' => array(
					'type' => 'string',
				),
				'blocklaneProMaxWidthCenter' => array(
					'type' => 'boolean',
					'default' => false,
				),
			),
		),
	),
	'extension:advanced-tabs' => array(
		array(
			'blocks' => array(
				'core/tab-panel',
			),
			'attributes' => array(
				'blocklaneProTabDescription' => array(
					'type' => 'string',
					'default' => '',
				),
			),
		),
		array(
			'blocks' => array(
				'core/tab-list',
			),
			'attributes' => array(
				'blocklaneProTabDescriptionFontSize' => array(
					'type' => 'string',
					'default' => '',
				),
			),
		),
		array(
			'blocks' => array(
				'core/tabs',
			),
			'attributes' => array(
				'blocklaneProTabListPosition' => array(
					'type' => 'string',
					'default' => '',
				),
				'blocklaneProTabListVerticalAlignment' => array(
					'type' => 'string',
					'default' => '',
				),
				'blocklaneProTabListWidth' => array(
					'type' => 'number',
					'default' => 0,
				),
				'blocklaneProTabDescriptionsAlwaysVisible' => array(
					'type' => 'boolean',
					'default' => false,
				),
			),
		),
	),
	'extension:animation-designer' => array(
		array(
			'blocks' => array(
				'core/group',
				'core/heading',
				'core/paragraph',
				'core/column',
				'core/columns',
				'core/image',
				'core/buttons',
				'core/cover',
				'core/post-template',
			),
			'attributes' => array(
				'animationType' => array(
					'type' => 'string',
					'default' => '',
				),
				'animationDuration' => array(
					'type' => 'number',
					'default' => 1,
				),
				'animationDelay' => array(
					'type' => 'number',
					'default' => 0,
				),
				'animationDistance' => array(
					'type' => 'number',
					'default' => 30,
				),
				'animationScale' => array(
					'type' => 'number',
					'default' => 1.05,
				),
				'animateOnScroll' => array(
					'type' => 'boolean',
					'default' => false,
				),
				'animateOnce' => array(
					'type' => 'boolean',
					'default' => true,
				),
				'scrollOffset' => array(
					'type' => 'number',
					'default' => -50,
				),
				'animationPresetId' => array(
					'type' => 'string',
					'default' => '',
				),
				'animateSequentially' => array(
					'type' => 'boolean',
					'default' => false,
				),
				'sequentialDelay' => array(
					'type' => 'number',
					'default' => 0.2,
				),
				'wordDelay' => array(
					'type' => 'number',
					'default' => 0.2,
				),
			),
		),
	),
	'extension:button-icons' => array(
		array(
			'blocks' => array(
				'core/button',
			),
			'attributes' => array(
				'icon' => array(
					'type' => 'string',
				),
				'iconPositionLeft' => array(
					'type' => 'boolean',
					'default' => false,
				),
				'iconWeight' => array(
					'type' => 'string',
					'default' => 'regular',
				),
				'iconColor' => array(
					'type' => 'string',
				),
				'customIconColor' => array(
					'type' => 'string',
				),
				'iconSize' => array(
					'type' => 'string',
				),
				'iconSpacing' => array(
					'type' => 'string',
				),
				'customIconSvg' => array(
					'type' => 'string',
					'default' => '',
				),
			),
		),
	),
	'extension:class-manager' => array(
		array(
			'blocks' => '*',
			'attributes' => array(
				'blocklaneProCustomClasses' => array(
					'type' => 'array',
					'default' => array(),
				),
			),
		),
	),
	'extension:hover-colors' => array(
		array(
			'blocks' => array(
				'support' => 'color.text',
			),
			'attributes' => array(
				'hoverTextColor' => array(
					'type' => 'string',
				),
				'customHoverTextColor' => array(
					'type' => 'string',
				),
				'hoverBackgroundColor' => array(
					'type' => 'string',
				),
				'customHoverBackgroundColor' => array(
					'type' => 'string',
				),
				'hoverBorderColor' => array(
					'type' => 'string',
				),
				'customHoverBorderColor' => array(
					'type' => 'string',
				),
				'hoverTransitionDuration' => array(
					'type' => 'number',
					'default' => 200,
				),
				'hoverTransitionTiming' => array(
					'type' => 'string',
					'default' => 'ease',
				),
			),
		),
	),
	'extension:paragraph-hover-decoration' => array(
		array(
			'blocks' => array(
				'core/paragraph',
				'core/heading',
				'core/button',
			),
			'attributes' => array(
				'textDecorationHover' => array(
					'type' => 'string',
					'default' => '',
				),
			),
		),
	),
	'extension:popup-binding' => array(
		array(
			'blocks' => array(
				'core/image',
				'core/cover',
			),
			'attributes' => array(
				'blocklaneProPopupId' => array(
					'type' => 'number',
					'default' => 0,
				),
			),
		),
		array(
			'blocks' => array(
				'core/button',
			),
			'attributes' => array(
				'blocklaneProPopupClose' => array(
					'type' => 'boolean',
					'default' => false,
				),
			),
		),
	),
	'extension:responsive-controls' => array(
		array(
			'blocks' => array(
				'core/paragraph',
				'core/heading',
				'core/list',
				'core/quote',
				'core/button',
				'core/site-title',
				'core/group',
				'core/columns',
				'core/column',
				'core/cover',
				'core/buttons',
				'core/post-content',
				'core/site-logo',
				'core/navigation',
				'core/image',
				'core/social-links',
				'core/search',
				'core/separator',
				'core/spacer',
			),
			'attributes' => array(
				'blocklaneProResponsive' => array(
					'type' => 'object',
					'default' => array(),
				),
			),
		),
	),
	'extension:smart-sync' => array(
		array(
			'blocks' => array(
				'core/columns',
				'core/group',
			),
			'attributes' => array(
				'smartSync' => array(
					'type' => 'boolean',
					'default' => false,
				),
			),
		),
	),
	'extension:text-wrap' => array(
		array(
			'blocks' => array(
				'core/paragraph',
				'core/heading',
				'core/list',
				'core/post-title',
				'core/post-excerpt',
			),
			'attributes' => array(
				'textWrap' => array(
					'type' => 'string',
					'default' => '',
				),
			),
		),
	),
	'extension:transparent-header' => array(
		array(
			'blocks' => array(
				'core/group',
			),
			'attributes' => array(
				'blocklaneProTransparentHeader' => array(
					'type' => 'boolean',
					'default' => false,
				),
				'blocklaneProThBackground' => array(
					'type' => 'string',
					'default' => '',
				),
				'blocklaneProTransparentSolidOnScroll' => array(
					'type' => 'boolean',
					'default' => true,
				),
				'blocklaneProTransparentTopOffset' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentZIndex' => array(
					'type' => 'number',
				),
				'blocklaneProTransparentBackground' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentTextColor' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentLogo' => array(
					'type' => 'string',
				),
			),
		),
		array(
			'blocks' => array(
				'core/group',
			),
			'attributes' => array(
				'blocklaneProThSolidBackground' => array(
					'type' => 'string',
				),
			),
		),
		array(
			'blocks' => array(
				'core/navigation',
			),
			'attributes' => array(
				'blocklaneProTransparentTextColor' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentHoverColor' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentCurrentColor' => array(
					'type' => 'string',
				),
			),
		),
		array(
			'blocks' => array(
				'core/site-title',
				'core/site-tagline',
				'core/search',
				'core/loginout',
			),
			'attributes' => array(
				'blocklaneProTransparentTextColor' => array(
					'type' => 'string',
				),
			),
		),
		array(
			'blocks' => array(
				'core/button',
			),
			'attributes' => array(
				'blocklaneProTransparentTextColor' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentBackground' => array(
					'type' => 'string',
				),
			),
		),
		array(
			'blocks' => array(
				'core/social-links',
			),
			'attributes' => array(
				'blocklaneProTransparentIconColor' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentIconBackground' => array(
					'type' => 'string',
				),
			),
		),
		array(
			'blocks' => array(
				'core/site-logo',
			),
			'attributes' => array(
				'blocklaneProTransparentLogo' => array(
					'type' => 'string',
				),
				'blocklaneProTransparentLogoId' => array(
					'type' => 'number',
				),
			),
		),
	),
	'extension:video-modal' => array(
		array(
			'blocks' => array(
				'core/cover',
				'core/button',
				'core/image',
			),
			'attributes' => array(
				'blocklaneProVideoModal' => array(
					'type' => 'boolean',
					'default' => false,
				),
				'blocklaneProVideoSource' => array(
					'type' => 'string',
					'default' => 'youtube',
				),
				'blocklaneProVideoUrl' => array(
					'type' => 'string',
					'default' => '',
				),
				'blocklaneProVideoId' => array(
					'type' => 'number',
					'default' => 0,
				),
				'blocklaneProVideoAutoplay' => array(
					'type' => 'boolean',
					'default' => true,
				),
				'blocklaneProVideoStartTime' => array(
					'type' => 'number',
					'default' => 0,
				),
				'blocklaneProPlayIcon' => array(
					'type' => 'string',
					'default' => 'always',
				),
			),
		),
	),
);
