<?php
/**
 * Edition — which artifact is running, and which units it contains.
 *
 * One tree produces two plugins: `blocklane-pro` (every unit) and `blocklane`
 * (the wordpress.org build, a subset). The difference is PHYSICAL — the free
 * zip does not contain the Pro units' files at all, because guideline 5
 * prohibits "functionality that is restricted or locked, only to be made
 * available by payment or upgrade". A BLOCKLANE_FREE constant with the code
 * still present IS that prohibited case, which is why the edition is baked
 * into the artifact rather than evaluated at runtime.
 *
 * The facts live in inc/edition.php, GENERATED by bin/generate-edition.php
 * from edition-manifest.json — the classmap precedent: the pro rendering is
 * committed and a stale copy fails the wiring check and the dist build; the
 * free rendering is written into the staging copy only, so the working tree
 * (and the dev site) always runs pro.
 *
 * has() is deliberately strict. Every unit the manifest knows about appears
 * in the data file, present or absent, so an unknown id is a TYPO in our own
 * source rather than a feature that happens to be missing — a defect, thrown,
 * never a silent false. That is the Content_Toggle posture applied here.
 *
 * Two consumers cannot use this class and read inc/edition.php directly, each
 * with a MIRROR CONTRACT comment naming this file: uninstall.php (runs with no
 * autoloader) and inc/extensions/loader/runtime-helpers.php (the front-end
 * runtimes are kept free of plugin classes by ARCHITECTURE.md's rule).
 *
 * @package blocklane_pro
 */

namespace blocklane_pro;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Edition {

	/**
	 * The generated facts, loaded once.
	 *
	 * @var array<string, mixed>|null
	 */
	private static ?array $data = null;

	/**
	 * Read inc/edition.php once.
	 *
	 * No fallback on purpose: an unreadable or malformed edition file must
	 * fatal here rather than degrade to "every unit is absent", which would
	 * silently strip the running site down to nothing.
	 *
	 * @return array<string, mixed>
	 */
	private static function data(): array {
		if ( null === self::$data ) {
			/** @var array<string, mixed> $loaded */
			$loaded     = require BLOCKLANE_PRO_PATH . '/inc/edition.php';
			self::$data = $loaded;
		}
		return self::$data;
	}

	/**
	 * This artifact's edition id: 'pro' or 'free'.
	 */
	public static function id(): string {
		return (string) self::data()['edition'];
	}

	/**
	 * Whether this artifact contains a unit.
	 *
	 * @param string $unit Manifest unit id, e.g. 'module:seo'.
	 * @throws \LogicException When the id is not in the manifest — a source defect.
	 */
	public static function has( string $unit ): bool {
		$units = self::data()['units'];
		if ( ! array_key_exists( $unit, $units ) ) {
			// esc_html + brackets: see Content_Toggle::resolve() for why the
			// escape is a no-op on every legal unit id.
			throw new \LogicException(
				esc_html( 'Blocklane: unknown edition unit [' . $unit . ']; add it to edition-manifest.json, or fix the typo.' )
			);
		}
		return false !== $units[ $unit ];
	}

	/**
	 * Whether this artifact contains a unit in a particular role.
	 *
	 * A unit can be present in one edition with fewer roles than in another:
	 * content-types ships its render runtime in free (role `content`) so
	 * Pro-authored types keep working, while its management half (`boot`,
	 * `lifecycle`, `admin`) is pro-only.
	 *
	 * @param string $unit Manifest unit id.
	 * @param string $role One of: content, lifecycle, admin, boot, uninstall.
	 * @throws \LogicException When the unit id is not in the manifest.
	 */
	public static function has_role( string $unit, string $role ): bool {
		if ( ! self::has( $unit ) ) {
			return false;
		}
		/** @var list<string> $roles */
		$roles = self::data()['units'][ $unit ];
		return in_array( $role, $roles, true );
	}

	/**
	 * Every unit this artifact contains, id => its roles here.
	 *
	 * @return array<string, list<string>>
	 */
	public static function units(): array {
		$present = array();
		foreach ( self::data()['units'] as $unit => $roles ) {
			if ( false !== $roles ) {
				$present[ $unit ] = $roles;
			}
		}
		return $present;
	}

	/**
	 * The presentation catalog for units this artifact does NOT contain —
	 * id => array{kind, label, blurb}. Empty in pro.
	 *
	 * Strings only, and the generator's token check proves it: this is what
	 * the free dashboard's single Pro card reads, and no functional code may
	 * ride along with it (that would be the guideline 5 case again).
	 *
	 * @return array<string, array{kind: string, label: string, blurb: string}>
	 */
	public static function absent(): array {
		/** @var array<string, array{kind: string, label: string, blurb: string}> $absent */
		$absent = self::data()['absent'];
		return $absent;
	}

	/** This artifact's display name — 'Blocklane Pro' or 'Blocklane'. */
	public static function name(): string {
		return (string) self::data()['name'];
	}

	/** This artifact's directory slug — 'blocklane-pro' or 'blocklane'. */
	public static function slug(): string {
		return (string) self::data()['slug'];
	}

	/**
	 * The unit an Advanced toggle belongs to, or null for a toggle no unit
	 * declares (a shared toggle both editions carry). Rendered from every
	 * unit's `toggle` in the manifest, so a store can refuse a key for a unit
	 * this edition does not carry before writing it (#844).
	 *
	 * @param string $toggle Advanced toggle slug.
	 * @return string|null Unit id, or null.
	 */
	public static function toggle_unit( string $toggle ): ?string {
		$toggles = (array) ( self::data()['toggles'] ?? array() );
		return isset( $toggles[ $toggle ] ) ? (string) $toggles[ $toggle ] : null;
	}

	/**
	 * Where the free edition's one Pro card links. '' in pro.
	 *
	 * A static URL with a static UTM and nothing else: guideline 11 permits
	 * the upsell link but forbids tracking referrals through it, so no
	 * per-install identifier and no click reporting may ever be added here.
	 */
	public static function pro_url(): string {
		return (string) self::data()['pro_url'];
	}

	/**
	 * The text domain — 'blocklane' in both editions. Rendered so the sibling
	 * marks can compare against data rather than a string in the code.
	 */
	public static function text_domain(): string {
		return (string) self::data()['text_domain'];
	}

	/**
	 * This edition's RANK — the higher edition runs when both are active.
	 *
	 * Ranks come from the manifest (pro 2, free 1) and are the only thing the
	 * coexistence guard compares; it reads them out of both rendered files
	 * through inc/edition-identity.php, so nothing in the runtime knows an
	 * edition by name and a third edition would need only a manifest line.
	 */
	public static function rank(): int {
		return (int) self::data()['rank'];
	}

	/**
	 * Whether this is the top-ranked edition — the one nothing can outrank,
	 * which is why its guard never scans for a higher build.
	 */
	public static function top(): bool {
		return (bool) self::data()['top'];
	}

	/**
	 * The OTHER edition's plugin basename AS THE MANIFEST EXPECTS IT, e.g.
	 * 'blocklane/blocklane.php'.
	 *
	 * A rendered hint for the battery and for support, not evidence: the
	 * operator may have unpacked the other edition under any folder name, so
	 * no door may decide from this value — a sibling is resolved by CONTENT
	 * (inc/edition-identity.php reads the candidate's own inc/edition.php).
	 * No code reads it: the guard, the sibling doors and uninstall all moved
	 * to content (Spec B); it stays rendered for support.
	 */
	public static function other_main(): string {
		return (string) self::data()['other_main'];
	}

	/**
	 * The other edition's wordpress.org slug, or '' when it is not hosted
	 * there.
	 *
	 * Only the directory build has a slug the world can fetch, so this answers
	 * 'blocklane' in Pro and '' in the free build — which is the whole control
	 * on inc/edition-sibling.php's installer: Pro may pull the free plugin down
	 * from wordpress.org, and free can never try to pull Pro, because Pro is
	 * not there to pull. The manifest declares it (`"wporg": true`); nothing in
	 * the runtime knows an edition by name.
	 */
	public static function other_wporg(): string {
		return (string) self::data()['other_wporg'];
	}

	/**
	 * The wordpress.org ACCOUNT that owns the sibling's listing, or '' when
	 * there is not one yet.
	 *
	 * This is what authorizes inc/edition-sibling.php's installer, and the
	 * reason it is an account rather than anything about the plugin itself: a
	 * directory slug is first-come, and every mark inside a published zip — the
	 * name, the text domain, a marker file — can be copied out of it by anyone
	 * who downloads it. Only the directory knows who OWNS a listing, and it
	 * reports that in the API response. So the installer asks "does
	 * wordpress.org say this listing is ours?" and this is the answer it checks
	 * against.
	 *
	 * Empty means the installer does nothing at all rather than trusting the slug
	 * on its own. The manifest carries the account (pending registration at the
	 * time of writing), so Pro builds from this tree have the installer LIVE; a
	 * name that turns out wrong fails as "refuses to install our own plugin",
	 * logged daily, never as "installs someone else's" (#816).
	 */
	public static function other_wporg_author(): string {
		return (string) self::data()['other_wporg_author'];
	}

	/**
	 * This edition's own uninstall fragments: unit id => path relative to the
	 * plugin root, only for units present here WITH the uninstall role.
	 *
	 * @return array<string, string>
	 */
	public static function uninstall_fragments(): array {
		return (array) self::data()['uninstall_fragments'];
	}

	/**
	 * The edition-qualified version stamp Version_Migration stores, e.g.
	 * 'pro/0.11.4'. Qualified so a site moving between editions at one version
	 * still reads as changed and the new edition's seeds run.
	 */
	public static function stamp(): string {
		return self::id() . '/' . BLOCKLANE_PRO_VERSION;
	}
}
