<?php
/**
 * GENERATED by bin/generate-edition.php from edition-manifest.json - DO NOT EDIT.
 * Regenerate after any manifest change; bin/wiring-check.php fails Quality CI and
 * the dist build when this file is stale.
 *
 * THE CATALOG'S TRANSLATED STRINGS: unit id => its label and blurb, each a
 * __() call on a literal, so `wp i18n make-pot` and GlotPress see every msgid.
 * Required ONLY by blocklane_pro\Settings::absent_catalog(), at
 * admin-enqueue time — never before `init`, which is why inc/edition.php (read
 * at plugin load) carries the same strings as plain data instead.
 *
 * Every cataloged unit is here in BOTH editions: the msgid set is a property
 * of the manifest, not of the artifact.
 *
 * @package blocklane_pro
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'block:form-file' => array(
		'label' => __( 'File Upload Field', 'blocklane' ),
		'blurb' => __( 'Let visitors attach files to a submission, with type and size limits, stored under your site\'s own upload policy.', 'blocklane' ),
	),
	'block:form-step' => array(
		'label' => __( 'Form Steps', 'blocklane' ),
		'blurb' => __( 'Split a form into steps with Back and Next, a progress bar, and one step validated at a time.', 'blocklane' ),
	),
	'extension:advanced-grid' => array(
		'label' => __( 'Advanced Grid Controls', 'blocklane' ),
		'blurb' => __( 'Per-breakpoint control over core\'s Grid block.', 'blocklane' ),
	),
	'extension:advanced-group' => array(
		'label' => __( 'Advanced Group Controls', 'blocklane' ),
		'blurb' => __( 'Hide a sticky header on scroll down, make a whole group clickable, and cap its width.', 'blocklane' ),
	),
	'extension:advanced-tabs' => array(
		'label' => __( 'Advanced Tabs', 'blocklane' ),
		'blurb' => __( 'Descriptions under the triggers of core\'s Tabs block.', 'blocklane' ),
	),
	'extension:ai-content' => array(
		'label' => __( 'Rewrite with AI', 'blocklane' ),
		'blurb' => __( 'Rewrite selected content in place from the editor toolbar.', 'blocklane' ),
	),
	'extension:animation-designer' => array(
		'label' => __( 'Animation Designer', 'blocklane' ),
		'blurb' => __( 'Fade and directional entrance animations with duration, delay and distance.', 'blocklane' ),
	),
	'extension:background-url' => array(
		'label' => __( 'Background Image URL', 'blocklane' ),
		'blurb' => __( 'Point a block\'s background at an external URL.', 'blocklane' ),
	),
	'extension:button-icons' => array(
		'label' => __( 'Button Icons', 'blocklane' ),
		'blurb' => __( 'An icon on any core Button block.', 'blocklane' ),
	),
	'extension:class-manager' => array(
		'label' => __( 'CSS Class Manager', 'blocklane' ),
		'blurb' => __( 'A registry of your CSS classes with a site-wide usage map.', 'blocklane' ),
	),
	'extension:cover-term-image' => array(
		'label' => __( 'Cover Term Image', 'blocklane' ),
		'blurb' => __( 'A Cover block inside a Terms Query renders the term\'s own image.', 'blocklane' ),
	),
	'extension:hover-colors' => array(
		'label' => __( 'Hover Colors', 'blocklane' ),
		'blurb' => __( 'Hover background, text and border colors with a transition and easing.', 'blocklane' ),
	),
	'extension:icon-library' => array(
		'label' => __( 'Icon Library', 'blocklane' ),
		'blurb' => __( 'A 1,500-icon cloud library plus your own SVGs, saved into core\'s Icon block.', 'blocklane' ),
	),
	'extension:paragraph-hover-decoration' => array(
		'label' => __( 'Decoration Hover', 'blocklane' ),
		'blurb' => __( 'The text-decoration shown on hover for paragraphs, headings and buttons.', 'blocklane' ),
	),
	'extension:pattern-editing' => array(
		'label' => __( 'Edit Patterns Freely', 'blocklane' ),
		'blurb' => __( 'Opt out of WordPress 7.0\'s content-only editing for unsynced patterns.', 'blocklane' ),
	),
	'extension:popup-binding' => array(
		'label' => __( 'Popup Bindings', 'blocklane' ),
		'blurb' => __( 'Bind a Button, Image, Cover or Navigation Link to open a popup — no hand-typed classes.', 'blocklane' ),
	),
	'extension:smart-sync' => array(
		'label' => __( 'Smart Sync', 'blocklane' ),
		'blurb' => __( 'Mirror a style change onto matching sibling blocks.', 'blocklane' ),
	),
	'extension:text-wrap' => array(
		'label' => __( 'Text Wrap', 'blocklane' ),
		'blurb' => __( 'Balanced and pretty text wrapping on dynamic text blocks.', 'blocklane' ),
	),
	'extension:video-modal' => array(
		'label' => __( 'Video Modal', 'blocklane' ),
		'blurb' => __( 'Play a video in a lightbox from a Button, Image or Cover.', 'blocklane' ),
	),
	'module:ai-mcp' => array(
		'label' => __( 'Blocklane AI MCP', 'blocklane' ),
		'blurb' => __( 'Connect the site to an external AI client through the Abilities API and MCP.', 'blocklane' ),
	),
	'module:ai-tools' => array(
		'label' => __( 'Blocklane AI Tools', 'blocklane' ),
		'blurb' => __( 'In-editor AI rewriting, running on your own AI provider.', 'blocklane' ),
	),
	'module:carousel' => array(
		'label' => __( 'Carousel', 'blocklane' ),
		'blurb' => __( 'A block-native slider with arrows, dots and autoplay.', 'blocklane' ),
	),
	'module:content-types' => array(
		'label' => __( 'Content Types', 'blocklane' ),
		'blurb' => __( 'Custom post types, taxonomies and fields with a real UI — replaces ACF, CPT UI and Pods.', 'blocklane' ),
	),
	'module:dynamic-values' => array(
		'label' => __( 'Dynamic Values', 'blocklane' ),
		'blurb' => __( 'Define a value once and bind blocks to it across the site.', 'blocklane' ),
	),
	'module:menu-designer' => array(
		'label' => __( 'Mega Menu', 'blocklane' ),
		'blurb' => __( 'Full-width menu panels built from template parts, with a mobile replacement.', 'blocklane' ),
	),
	'popups:pro' => array(
		'label' => __( 'Popup Triggers and Targeting', 'blocklane' ),
		'blurb' => __( 'Open popups on scroll depth or exit intent, and show them on the front page, by post type, by URL path, or to logged-in visitors only.', 'blocklane' ),
	),
	'security:auto-update-plugins' => array(
		'label' => __( 'Auto-Update Plugins', 'blocklane' ),
		'blurb' => __( 'Install plugin updates automatically as they ship.', 'blocklane' ),
	),
	'security:auto-update-themes' => array(
		'label' => __( 'Auto-Update Themes', 'blocklane' ),
		'blurb' => __( 'Install theme updates automatically as they ship.', 'blocklane' ),
	),
	'service:scripts' => array(
		'label' => __( 'Custom Scripts', 'blocklane' ),
		'blurb' => __( 'Add header, body and footer code to every page: analytics, pixels and verification tags.', 'blocklane' ),
	),
);
