<?php
/**
 * GENERATED by bin/generate-edition.php from edition-manifest.json - DO NOT EDIT.
 * Regenerate after any manifest change; bin/wiring-check.php fails Quality CI and
 * the dist build when this file is stale.
 *
 * Which artifact this is, and which units it contains. Read through
 * blocklane_pro\Edition (inc/class-blocklane-pro-edition.php); uninstall.php and
 * the extensions runtime read it directly under a MIRROR CONTRACT.
 *
 * DATA ONLY. No functional code may appear here: this file carries the free
 * build's Pro catalog, and code riding alongside it would be the
 * ship-it-behind-a-flag case guideline 5 prohibits.
 *
 * @package blocklane_pro
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'edition'     => 'free',
	'slug'        => 'blocklane',
	'name'        => 'Blocklane',
	'main'        => 'blocklane.php',
	'text_domain' => 'blocklane',
	'other_main'  => 'blocklane-pro/blocklane-pro.php',
	'wporg'       => true,
	'other_wporg' => '',
	'other_wporg_author' => '',
	'pro_url'     => 'https://blocklanewp.com/pricing/?utm_source=blocklane-free&utm_medium=plugin',
	'rank'        => 1,
	'top'         => false,
	'toggles'     => array(
		'ai-mcp' => 'module:ai-mcp',
		'ai-tools' => 'module:ai-tools',
		'carousel' => 'module:carousel',
		'child-theme-tool' => 'service:child-theme',
		'content-types' => 'module:content-types',
		'dynamic-values' => 'module:dynamic-values',
		'forms' => 'module:forms',
		'popups' => 'module:popups',
		'scripts' => 'service:scripts',
		'seo' => 'module:seo',
		'site-privacy' => 'module:site-lock',
	),
	'contributions' => array(
		'blocks' => array(
			'blocklane/form-file' => 'block:form-file',
			'blocklane/form-step' => 'block:form-step',
		),
		'popups.condition' => array(
			'front-page' => 'popups:pro',
			'logged-in' => 'popups:pro',
			'post-type' => 'popups:pro',
			'url' => 'popups:pro',
		),
		'popups.trigger' => array(
			'exit' => 'popups:pro',
			'scroll' => 'popups:pro',
		),
		'security.setting' => array(
			'auto-update-plugins' => 'security:auto-update-plugins',
			'auto-update-themes' => 'security:auto-update-themes',
		),
	),
	'uninstall_fragments' => array(),
	'units'       => array(
		'sibling' => false,
		'gateway' => false,
		'license' => false,
		'updates' => false,
		'module:extensions' => array( 'content', 'lifecycle', 'boot' ),
		'extension:responsive-controls' => array( 'content' ),
		'extension:transparent-header' => array( 'content' ),
		'extension:advanced-group' => false,
		'extension:advanced-grid' => false,
		'extension:animation-designer' => false,
		'extension:hover-colors' => false,
		'extension:button-icons' => false,
		'extension:icon-library' => false,
		'extension:advanced-tabs' => false,
		'extension:text-wrap' => false,
		'extension:video-modal' => false,
		'extension:background-url' => false,
		'extension:paragraph-hover-decoration' => false,
		'extension:class-manager' => false,
		'extension:smart-sync' => false,
		'extension:cover-term-image' => false,
		'extension:pattern-editing' => false,
		'extension:popup-binding' => false,
		'extension:ai-content' => false,
		'module:seo' => array( 'content', 'lifecycle', 'boot' ),
		'module:forms' => array( 'content', 'boot' ),
		'block:form-step' => false,
		'block:form-file' => false,
		'module:popups' => array( 'content', 'lifecycle', 'boot' ),
		'popups:pro' => false,
		'module:site-lock' => array( 'lifecycle', 'boot' ),
		'module:security' => array( 'lifecycle', 'boot' ),
		'security:auto-update-plugins' => false,
		'security:auto-update-themes' => false,
		'module:advanced' => array( 'boot' ),
		'service:textdomain' => false,
		'service:scripts' => false,
		'service:child-theme' => array( 'lifecycle', 'admin' ),
		'runtime:content-types' => array( 'content', 'lifecycle' ),
		'module:content-types' => false,
		'runtime:dynamic-values' => array( 'content' ),
		'module:dynamic-values' => false,
		'runtime:mega-menu-standin' => array( 'content' ),
		'runtime:form-step-standin' => array( 'content' ),
		'runtime:icon-collection' => array( 'content' ),
		'module:carousel' => false,
		'module:menu-designer' => false,
		'module:ai-mcp' => false,
		'module:ai-tools' => false,
	),
	'absent'      => array(
		'extension:advanced-group' => array(
			'kind' => 'extension',
			'label' => 'Advanced Group Controls',
			'blurb' => 'Hide a sticky header on scroll down, make a whole group clickable, and cap its width.',
		),
		'extension:advanced-grid' => array(
			'kind' => 'extension',
			'label' => 'Advanced Grid Controls',
			'blurb' => 'Per-breakpoint control over core\'s Grid block.',
		),
		'extension:animation-designer' => array(
			'kind' => 'extension',
			'label' => 'Animation Designer',
			'blurb' => 'Fade and directional entrance animations with duration, delay and distance.',
		),
		'extension:hover-colors' => array(
			'kind' => 'extension',
			'label' => 'Hover Colors',
			'blurb' => 'Hover background, text and border colors with a transition and easing.',
		),
		'extension:button-icons' => array(
			'kind' => 'extension',
			'label' => 'Button Icons',
			'blurb' => 'An icon on any core Button block.',
		),
		'extension:icon-library' => array(
			'kind' => 'extension',
			'label' => 'Icon Library',
			'blurb' => 'A 1,500-icon cloud library plus your own SVGs, saved into core\'s Icon block.',
		),
		'extension:advanced-tabs' => array(
			'kind' => 'extension',
			'label' => 'Advanced Tabs',
			'blurb' => 'Descriptions under the triggers of core\'s Tabs block.',
		),
		'extension:text-wrap' => array(
			'kind' => 'extension',
			'label' => 'Text Wrap',
			'blurb' => 'Balanced and pretty text wrapping on dynamic text blocks.',
		),
		'extension:video-modal' => array(
			'kind' => 'extension',
			'label' => 'Video Modal',
			'blurb' => 'Play a video in a lightbox from a Button, Image or Cover.',
		),
		'extension:background-url' => array(
			'kind' => 'extension',
			'label' => 'Background Image URL',
			'blurb' => 'Point a block\'s background at an external URL.',
		),
		'extension:paragraph-hover-decoration' => array(
			'kind' => 'extension',
			'label' => 'Decoration Hover',
			'blurb' => 'The text-decoration shown on hover for paragraphs, headings and buttons.',
		),
		'extension:class-manager' => array(
			'kind' => 'extension',
			'label' => 'CSS Class Manager',
			'blurb' => 'A registry of your CSS classes with a site-wide usage map.',
		),
		'extension:smart-sync' => array(
			'kind' => 'extension',
			'label' => 'Smart Sync',
			'blurb' => 'Mirror a style change onto matching sibling blocks.',
		),
		'extension:cover-term-image' => array(
			'kind' => 'extension',
			'label' => 'Cover Term Image',
			'blurb' => 'A Cover block inside a Terms Query renders the term\'s own image.',
		),
		'extension:pattern-editing' => array(
			'kind' => 'extension',
			'label' => 'Edit Patterns Freely',
			'blurb' => 'Opt out of WordPress 7.0\'s content-only editing for unsynced patterns.',
		),
		'extension:popup-binding' => array(
			'kind' => 'extension',
			'label' => 'Popup Bindings',
			'blurb' => 'Bind a Button, Image, Cover or Navigation Link to open a popup — no hand-typed classes.',
		),
		'extension:ai-content' => array(
			'kind' => 'extension',
			'label' => 'Rewrite with AI',
			'blurb' => 'Rewrite selected content in place from the editor toolbar.',
		),
		'block:form-step' => array(
			'kind' => 'block',
			'label' => 'Form Steps',
			'blurb' => 'Split a form into steps with Back and Next, a progress bar, and one step validated at a time.',
		),
		'block:form-file' => array(
			'kind' => 'block',
			'label' => 'File Upload Field',
			'blurb' => 'Let visitors attach files to a submission, with type and size limits, stored under your site\'s own upload policy.',
		),
		'popups:pro' => array(
			'kind' => 'runtime',
			'label' => 'Popup Triggers and Targeting',
			'blurb' => 'Open popups on scroll depth or exit intent, and show them on the front page, by post type, by URL path, or to logged-in visitors only.',
		),
		'security:auto-update-plugins' => array(
			'kind' => 'runtime',
			'label' => 'Auto-Update Plugins',
			'blurb' => 'Install plugin updates automatically as they ship.',
		),
		'security:auto-update-themes' => array(
			'kind' => 'runtime',
			'label' => 'Auto-Update Themes',
			'blurb' => 'Install theme updates automatically as they ship.',
		),
		'service:scripts' => array(
			'kind' => 'service',
			'label' => 'Custom Scripts',
			'blurb' => 'Add header, body and footer code to every page: analytics, pixels and verification tags.',
		),
		'module:content-types' => array(
			'kind' => 'module',
			'label' => 'Content Types',
			'blurb' => 'Custom post types, taxonomies and fields with a real UI — replaces ACF, CPT UI and Pods.',
		),
		'module:dynamic-values' => array(
			'kind' => 'module',
			'label' => 'Dynamic Values',
			'blurb' => 'Define a value once and bind blocks to it across the site.',
		),
		'module:carousel' => array(
			'kind' => 'module',
			'label' => 'Carousel',
			'blurb' => 'A block-native slider with arrows, dots and autoplay.',
		),
		'module:menu-designer' => array(
			'kind' => 'module',
			'label' => 'Mega Menu',
			'blurb' => 'Full-width menu panels built from template parts, with a mobile replacement.',
		),
		'module:ai-mcp' => array(
			'kind' => 'module',
			'label' => 'Blocklane AI MCP',
			'blurb' => 'Connect the site to an external AI client through the Abilities API and MCP.',
		),
		'module:ai-tools' => array(
			'kind' => 'module',
			'label' => 'Blocklane AI Tools',
			'blurb' => 'In-editor AI rewriting, running on your own AI provider.',
		),
	),
);
